# using machine learning model -- XGBOOST

In [1]:
import pandas as pd
import numpy as np

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (1.7.0)
Requirement already satisfied: numpy>=1.22.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.2.0)
Requirement already satisfied: scipy>=1.8.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
df= pd.read_csv(r"C:\Downloads\Churn_Modelling.csv")

In [5]:
df=df.drop(columns=['RowNumber','CustomerId','Surname'],axis=1)

In [6]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [7]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [8]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [8]:
df['Gender'] = label_encoder.fit_transform(df['Gender']) 
# female=0 , male=1

In [9]:
df['Geography'] = label_encoder.fit_transform(df['Geography']) 
# france=0, spain=2, genmany=1

In [10]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,0,0,42,2,0.00,1,1,1,101348.88,1
1,608,2,0,41,1,83807.86,1,0,1,112542.58,0
2,502,0,0,42,8,159660.80,3,1,0,113931.57,1
3,699,0,0,39,1,0.00,2,0,0,93826.63,0
4,850,2,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,0,1,39,5,0.00,2,1,0,96270.64,0
9996,516,0,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,0,0,36,7,0.00,1,0,1,42085.58,1
9998,772,1,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,0,0,28,4,130142.79,1,1,0,38190.78,0

In [11]:
df.corr()['Exited']

CreditScore       -0.027094
Geography          0.035943
Gender            -0.106512
Age                0.285323
Tenure            -0.014001
Balance            0.118533
NumOfProducts     -0.047820
HasCrCard         -0.007138
IsActiveMember    -0.156128
EstimatedSalary    0.012097
Exited             1.000000
Name: Exited, dtype: float64

In [12]:
df2=df.drop(columns=['CreditScore','Gender','Tenure','NumOfProducts','HasCrCard','IsActiveMember'],axis=1)

In [13]:
x1= df2.iloc[:, :-1]
y1=df2.iloc[:, -1]

In [14]:
from sklearn.model_selection import train_test_split
X_train1, X_test1, y_train1, y_test1 = train_test_split(x1, y1, test_size=0.2, random_state=42)

In [15]:
# scalling 
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
x_train_scaled1 = scaler.fit_transform(X_train1)
x_test_scaled1= scaler.fit_transform(X_test1)

In [16]:
!pip install xgboost

Requirement already satisfied: xgboost in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (3.1.1)
Requirement already satisfied: numpy in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from xgboost) (2.2.0)
Requirement already satisfied: scipy in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from xgboost) (1.15.3)

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [17]:
x_train_scaled1

array([[-0.9055496 , -0.6557859 , -1.21847056,  1.36766974],
       [ 0.30164867,  0.29493847,  0.69683765,  1.6612541 ],
       [ 1.50884694, -1.41636539,  0.61862909, -0.25280688],
       ...,
       [-0.9055496 , -0.08535128, -1.21847056, -0.1427649 ],
       [-0.9055496 ,  0.3900109 ,  1.8272593 , -0.05082558],
       [ 0.30164867,  1.15059039,  1.1497197 , -0.81456811]],
      shape=(8000, 4))

In [18]:
from xgboost import XGBClassifier

In [19]:
model = XGBClassifier(objective='binary:logistic', 
                      n_estimators=100, 
                      learning_rate=0.1, 
                      max_depth=3, 
                      random_state=42,
                      use_label_encoder=False, 
                      eval_metric='logloss')

In [20]:
model.fit(x_train_scaled1,y_train1)

C:\Users\arind\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:199: UserWarning: [11:47:19] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, ...)

In [21]:
y_pred=model.predict(x_test_scaled1)

In [22]:
from sklearn.metrics import accuracy_score

In [23]:
accuracy=accuracy_score(y_test1,y_pred)

In [24]:
accuracy

0.8205

# USING deep learning model -- ANN

In [25]:
!pip install tensorflow

Requirement already satisfied: tensorflow in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (2.20.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.3.1)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (24.2)
Requirement already satisfied: protobuf>=5.28.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (5.29.5)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (3.2.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (4.14.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.0.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (1.73.1)
Requirement already satisfied: tensorboard~=2.20.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (3.12.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (2.2.0)
Requirement already satisfied: h5py>=3.11.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (3.15.1)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorflow) (0.5.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2025.6.15)
Requirement already satisfied: markdown>=2.6.8 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (3.10)
Requirement already satisfied: pillow in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (11.2.1)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (3.0.6)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from keras>=3.10.0->tensorflow) (14.0.0)
Requirement already satisfied: namex in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from keras>=3.10.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from keras>=3.10.0->tensorflow) (0.17.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from rich->keras>=3.10.0->tensorflow) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from rich->keras>=3.10.0->tensorflow) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.2)

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [26]:
from tensorflow import keras

In [27]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,Dropout
from tensorflow.keras.layers import BatchNormalization

In [99]:
model= Sequential()
model.add(Dense(128,activation="relu",input_dim=4))
model.add(BatchNormalization())
model.add(Dense(80,activation="tanh"))
model.add(Dense(64,activation="relu"))
model.add(Dropout(0.2))
model.add(Dense(32,activation="tanh"))
model.add(Dense(16,activation="relu"))
model.add(Dropout(0.1))
model.add(Dense(1,activation="sigmoid"))


# model = Sequential()
# model.add(Dense(128, activation="relu",input_dim=4))
# model.add(BatchNormalization())
# model.add(Dense(64, activation='relu'))
# model.add(Dropout(0.2))
# model.add(BatchNormalization())
# model.add(Dense(32, activation='relu'))
# model.add(Dropout(0.1))
# model.add(Dense(1, activation='sigmoid')

C:\Users\arind\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [100]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_20 (Dense)                     │ (None, 128)                 │             640 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_4                │ (None, 128)                 │             512 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_21 (Dense)                     │ (None, 80)                  │          10,320 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_22 (Dense)                     │ (None, 64)                  │           5,184 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_13 (Dropout)                 │ (None, 64)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_23 (Dense)                     │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_24 (Dense)                     │ (None, 16)                  │             528 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_14 (Dropout)                 │ (None, 16)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_25 (Dense)                     │ (None, 1)                   │              17 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 19,281 (75.32 KB)

 Trainable params: 19,025 (74.32 KB)

 Non-trainable params: 256 (1.00 KB)

In [101]:
from tensorflow.keras.optimizers import Adam
optimizer = Adam(learning_rate=1e-3)

In [102]:
model.compile(
    optimizer=optimizer,
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [103]:
from tensorflow.keras.callbacks import EarlyStopping,ReduceLROnPlateau
callbacks = [
    EarlyStopping(monitor='val_accuracy', patience=25, restore_best_weights=True, min_delta=0.005),
    ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=10, min_lr=1e-6, verbose=1)
]

In [106]:
model.fit(
    x_train_scaled1,y_train1,
    validation_split=0.2,
    epochs=500,
    batch_size=32,
    
    verbose=1
)

Epoch 1/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8184 - loss: 0.4191 - val_accuracy: 0.8062 - val_loss: 0.4329
Epoch 2/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8216 - loss: 0.4141 - val_accuracy: 0.8075 - val_loss: 0.4330
Epoch 3/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8191 - loss: 0.4173 - val_accuracy: 0.8087 - val_loss: 0.4330
Epoch 4/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8158 - loss: 0.4191 - val_accuracy: 0.8087 - val_loss: 0.4383
Epoch 5/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8175 - loss: 0.4150 - val_accuracy: 0.8081 - val_loss: 0.4330
Epoch 6/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8181 - loss: 0.4171 - val_accuracy: 0.8094 - val_loss: 0.4310
Epoch 7/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8202 - loss: 0.4163 - val_accuracy: 0.8012 - val_loss: 0.4405
Epoch 8/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8225 - loss: 0.4149 - val_accuracy: 0.8087 - val_loss: 0.4368
Epoch 9/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8177 - loss: 0.4182 - val_accuracy: 0.8069 - val_loss: 0.4386
Epoch 10/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8225 - loss: 0.4154 - val_accuracy: 0.8000 - val_loss: 0.4347
Epoch 11/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8186 - loss: 0.4162 - val_accuracy: 0.8081 - val_loss: 0.4344
Epoch 12/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8206 - loss: 0.4152 - val_accuracy: 0.8056 - val_loss: 0.4336
Epoch 13/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8169 - loss: 0.4189 - val_accuracy: 0.8106 - val_loss: 0.4345
Epoch 14/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8178 - loss: 0.4145 - val_accuracy: 0.8100 - val_loss: 0.4358
Epoch 15/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8206 - loss: 0.4159 - val_accuracy: 0.8037 - val_loss: 0.4368
Epoch 16/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8188 - loss: 0.4172 - val_accuracy: 0.8094 - val_loss: 0.4342
Epoch 17/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8198 - loss: 0.4135 - val_accuracy: 0.8100 - val_loss: 0.4328
Epoch 18/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8203 - loss: 0.4157 - val_accuracy: 0.8025 - val_loss: 0.4373
Epoch 19/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8197 - loss: 0.4142 - val_accuracy: 0.8025 - val_loss: 0.4371
Epoch 20/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8152 - loss: 0.4153 - val_accuracy: 0.8031 - val_loss: 0.4359
Epoch 21/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8194 - loss: 0.4126 - val_accuracy: 0.8087 - val_loss: 0.4361
Epoch 22/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8186 - loss: 0.4158 - val_accuracy: 0.8100 - val_loss: 0.4349
Epoch 23/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8181 - loss: 0.4125 - val_accuracy: 0.8075 - val_loss: 0.4358
Epoch 24/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8216 - loss: 0.4126 - val_accuracy: 0.8025 - val_loss: 0.4382
Epoch 25/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8197 - loss: 0.4165 - val_accuracy: 0.8037 - val_loss: 0.4322
Epoch 26/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8205 - loss: 0.4155 - val_accuracy: 0.8031 - val_loss: 0.4385
Epoch 27/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8195 - loss: 0.4118 - val_accuracy: 0.8069 - val_loss: 0.4352
Epoch 28/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8208 - loss: 0.4117 - val_accuracy: 0.8106 - val_loss: 0.4332
Epoch 29/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8227 - loss: 0.4084 - val_accuracy: 0.8031 - val_loss: 0.4381
Epoch 30/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8206 - loss: 0.4126 - val_accuracy: 0.8000 - val_loss: 0.4435
Epoch 31/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8228 - loss: 0.4144 - val_accuracy: 0.8037 - val_loss: 0.4325
Epoch 32/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8189 - loss: 0.4137 - val_accuracy: 0.8062 - val_loss: 0.4335
Epoch 33/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8241 - loss: 0.4108 - val_accuracy: 0.8012 - val_loss: 0.4387
Epoch 34/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8231 - loss: 0.4117 - val_accuracy: 0.8069 - val_loss: 0.4375
Epoch 35/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8216 - loss: 0.4116 - val_accuracy: 0.8044 - val_loss: 0.4392
Epoch 36/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8219 - loss: 0.4094 - val_accuracy: 0.8037 - val_loss: 0.4389
Epoch 37/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8225 - loss: 0.4108 - val_accuracy: 0.8006 - val_loss: 0.4404
Epoch 38/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8216 - loss: 0.4108 - val_accuracy: 0.8062 - val_loss: 0.4394
Epoch 39/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8247 - loss: 0.4116 - val_accuracy: 0.8075 - val_loss: 0.4391
Epoch 40/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8245 - loss: 0.4116 - val_accuracy: 0.8037 - val_loss: 0.4393
Epoch 41/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8230 - loss: 0.4080 - val_accuracy: 0.8012 - val_loss: 0.4436
Epoch 42/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8255 - loss: 0.4067 - val_accuracy: 0.8031 - val_loss: 0.4392
Epoch 43/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8258 - loss: 0.4080 - val_accuracy: 0.8044 - val_loss: 0.4408
Epoch 44/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8222 - loss: 0.4090 - val_accuracy: 0.8044 - val_loss: 0.4397
Epoch 45/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8233 - loss: 0.4119 - val_accuracy: 0.8056 - val_loss: 0.4387
Epoch 46/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8252 - loss: 0.4082 - val_accuracy: 0.8062 - val_loss: 0.4395
Epoch 47/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8222 - loss: 0.4092 - val_accuracy: 0.8100 - val_loss: 0.4399
Epoch 48/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8242 - loss: 0.4094 - val_accuracy: 0.8050 - val_loss: 0.4389
Epoch 49/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8203 - loss: 0.4115 - val_accuracy: 0.8050 - val_loss: 0.4404
Epoch 50/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8220 - loss: 0.4065 - val_accuracy: 0.8037 - val_loss: 0.4433
Epoch 51/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8247 - loss: 0.4074 - val_accuracy: 0.8012 - val_loss: 0.4444
Epoch 52/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8223 - loss: 0.4080 - val_accuracy: 0.8037 - val_loss: 0.4455
Epoch 53/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8250 - loss: 0.4072 - val_accuracy: 0.8050 - val_loss: 0.4411
Epoch 54/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8256 - loss: 0.4080 - val_accuracy: 0.8062 - val_loss: 0.4414
Epoch 55/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8225 - loss: 0.4085 - val_accuracy: 0.8056 - val_loss: 0.4424
Epoch 56/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8266 - loss: 0.4060 - val_accuracy: 0.8069 - val_loss: 0.4423
Epoch 57/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8188 - loss: 0.4066 - val_accuracy: 0.8050 - val_loss: 0.4422
Epoch 58/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8264 - loss: 0.4059 - val_accuracy: 0.8094 - val_loss: 0.4452
Epoch 59/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8269 - loss: 0.4052 - val_accuracy: 0.8044 - val_loss: 0.4452
Epoch 60/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8267 - loss: 0.4022 - val_accuracy: 0.8037 - val_loss: 0.4471
Epoch 61/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8266 - loss: 0.4051 - val_accuracy: 0.8044 - val_loss: 0.4490
Epoch 62/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8238 - loss: 0.4085 - val_accuracy: 0.8081 - val_loss: 0.4435
Epoch 63/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8238 - loss: 0.4041 - val_accuracy: 0.8075 - val_loss: 0.4461
Epoch 64/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8264 - loss: 0.4026 - val_accuracy: 0.8012 - val_loss: 0.4406
Epoch 65/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8239 - loss: 0.4035 - val_accuracy: 0.8094 - val_loss: 0.4447
Epoch 66/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8220 - loss: 0.4057 - val_accuracy: 0.8069 - val_loss: 0.4424
Epoch 67/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8239 - loss: 0.4027 - val_accuracy: 0.8050 - val_loss: 0.4437
Epoch 68/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8267 - loss: 0.4040 - val_accuracy: 0.8056 - val_loss: 0.4475
Epoch 69/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8241 - loss: 0.4048 - val_accuracy: 0.8087 - val_loss: 0.4502
Epoch 70/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8252 - loss: 0.4048 - val_accuracy: 0.8062 - val_loss: 0.4445
Epoch 71/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8266 - loss: 0.4023 - val_accuracy: 0.8050 - val_loss: 0.4442
Epoch 72/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8273 - loss: 0.3994 - val_accuracy: 0.8031 - val_loss: 0.4453
Epoch 73/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8234 - loss: 0.4026 - val_accuracy: 0.8025 - val_loss: 0.4428
Epoch 74/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8228 - loss: 0.4020 - val_accuracy: 0.8006 - val_loss: 0.4441
Epoch 75/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8247 - loss: 0.4041 - val_accuracy: 0.8050 - val_loss: 0.4446
Epoch 76/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8289 - loss: 0.4029 - val_accuracy: 0.8050 - val_loss: 0.4416
Epoch 77/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8277 - loss: 0.4028 - val_accuracy: 0.8037 - val_loss: 0.4456
Epoch 78/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8247 - loss: 0.4033 - val_accuracy: 0.8050 - val_loss: 0.4420
Epoch 79/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8252 - loss: 0.4016 - val_accuracy: 0.8050 - val_loss: 0.4503
Epoch 80/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8242 - loss: 0.4043 - val_accuracy: 0.7994 - val_loss: 0.4489
Epoch 81/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8236 - loss: 0.4027 - val_accuracy: 0.8037 - val_loss: 0.4476
Epoch 82/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8253 - loss: 0.4010 - val_accuracy: 0.8025 - val_loss: 0.4520
Epoch 83/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8272 - loss: 0.4027 - val_accuracy: 0.8037 - val_loss: 0.4441
Epoch 84/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8247 - loss: 0.4029 - val_accuracy: 0.8112 - val_loss: 0.4438
Epoch 85/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8278 - loss: 0.4000 - val_accuracy: 0.7987 - val_loss: 0.4472
Epoch 86/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8239 - loss: 0.4047 - val_accuracy: 0.8044 - val_loss: 0.4481
Epoch 87/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8266 - loss: 0.4031 - val_accuracy: 0.8006 - val_loss: 0.4473
Epoch 88/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8250 - loss: 0.4035 - val_accuracy: 0.8044 - val_loss: 0.4499
Epoch 89/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8263 - loss: 0.4007 - val_accuracy: 0.8019 - val_loss: 0.4446
Epoch 90/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8266 - loss: 0.4032 - val_accuracy: 0.8075 - val_loss: 0.4430
Epoch 91/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8250 - loss: 0.4007 - val_accuracy: 0.8025 - val_loss: 0.4471
Epoch 92/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8275 - loss: 0.4015 - val_accuracy: 0.8062 - val_loss: 0.4472
Epoch 93/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8220 - loss: 0.4025 - val_accuracy: 0.8012 - val_loss: 0.4478
Epoch 94/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8283 - loss: 0.4006 - val_accuracy: 0.8081 - val_loss: 0.4453
Epoch 95/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8263 - loss: 0.3997 - val_accuracy: 0.8069 - val_loss: 0.4447
Epoch 96/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8272 - loss: 0.4024 - val_accuracy: 0.8069 - val_loss: 0.4450
Epoch 97/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8280 - loss: 0.3985 - val_accuracy: 0.8062 - val_loss: 0.4445
Epoch 98/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8288 - loss: 0.3990 - val_accuracy: 0.8044 - val_loss: 0.4515
Epoch 99/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8272 - loss: 0.4008 - val_accuracy: 0.8044 - val_loss: 0.4510
Epoch 100/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8261 - loss: 0.3992 - val_accuracy: 0.8050 - val_loss: 0.4496
Epoch 101/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8294 - loss: 0.3973 - val_accuracy: 0.8006 - val_loss: 0.4527
Epoch 102/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8292 - loss: 0.3979 - val_accuracy: 0.8031 - val_loss: 0.4474
Epoch 103/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8297 - loss: 0.3967 - val_accuracy: 0.8037 - val_loss: 0.4468
Epoch 104/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8252 - loss: 0.3969 - val_accuracy: 0.8050 - val_loss: 0.4503
Epoch 105/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8269 - loss: 0.3985 - val_accuracy: 0.8044 - val_loss: 0.4455
Epoch 106/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8280 - loss: 0.3975 - val_accuracy: 0.8031 - val_loss: 0.4438
Epoch 107/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8295 - loss: 0.3983 - val_accuracy: 0.8050 - val_loss: 0.4481
Epoch 108/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8300 - loss: 0.4012 - val_accuracy: 0.8062 - val_loss: 0.4490
Epoch 109/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8292 - loss: 0.3965 - val_accuracy: 0.8069 - val_loss: 0.4472
Epoch 110/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8267 - loss: 0.3988 - val_accuracy: 0.8087 - val_loss: 0.4483
Epoch 111/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8258 - loss: 0.3983 - val_accuracy: 0.8044 - val_loss: 0.4455
Epoch 112/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8277 - loss: 0.4019 - val_accuracy: 0.8094 - val_loss: 0.4445
Epoch 113/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8239 - loss: 0.3994 - val_accuracy: 0.8075 - val_loss: 0.4457
Epoch 114/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8275 - loss: 0.3950 - val_accuracy: 0.8037 - val_loss: 0.4527
Epoch 115/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8278 - loss: 0.4007 - val_accuracy: 0.8044 - val_loss: 0.4553
Epoch 116/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8267 - loss: 0.3956 - val_accuracy: 0.8037 - val_loss: 0.4558
Epoch 117/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8259 - loss: 0.4016 - val_accuracy: 0.8087 - val_loss: 0.4519
Epoch 118/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8252 - loss: 0.3998 - val_accuracy: 0.8069 - val_loss: 0.4500
Epoch 119/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8281 - loss: 0.3971 - val_accuracy: 0.8050 - val_loss: 0.4490
Epoch 120/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8292 - loss: 0.3978 - val_accuracy: 0.8056 - val_loss: 0.4491
Epoch 121/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8281 - loss: 0.3973 - val_accuracy: 0.8044 - val_loss: 0.4482
Epoch 122/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8281 - loss: 0.3982 - val_accuracy: 0.8031 - val_loss: 0.4551
Epoch 123/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8273 - loss: 0.3969 - val_accuracy: 0.8044 - val_loss: 0.4539
Epoch 124/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8302 - loss: 0.3955 - val_accuracy: 0.8062 - val_loss: 0.4540
Epoch 125/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8311 - loss: 0.3964 - val_accuracy: 0.8094 - val_loss: 0.4563
Epoch 126/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8283 - loss: 0.3965 - val_accuracy: 0.8025 - val_loss: 0.4524
Epoch 127/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8298 - loss: 0.3964 - val_accuracy: 0.8069 - val_loss: 0.4526
Epoch 128/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8281 - loss: 0.3974 - val_accuracy: 0.8087 - val_loss: 0.4539
Epoch 129/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8252 - loss: 0.3959 - val_accuracy: 0.8062 - val_loss: 0.4476
Epoch 130/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8283 - loss: 0.3957 - val_accuracy: 0.8044 - val_loss: 0.4512
Epoch 131/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8284 - loss: 0.3971 - val_accuracy: 0.8094 - val_loss: 0.4541
Epoch 132/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8272 - loss: 0.3932 - val_accuracy: 0.8037 - val_loss: 0.4514
Epoch 133/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8297 - loss: 0.3949 - val_accuracy: 0.8100 - val_loss: 0.4510
Epoch 134/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8281 - loss: 0.3990 - val_accuracy: 0.8081 - val_loss: 0.4478
Epoch 135/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8302 - loss: 0.3961 - val_accuracy: 0.8100 - val_loss: 0.4500
Epoch 136/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8298 - loss: 0.3969 - val_accuracy: 0.8037 - val_loss: 0.4524
Epoch 137/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8303 - loss: 0.3952 - val_accuracy: 0.8075 - val_loss: 0.4502
Epoch 138/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8278 - loss: 0.3941 - val_accuracy: 0.8075 - val_loss: 0.4497
Epoch 139/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8269 - loss: 0.3949 - val_accuracy: 0.8069 - val_loss: 0.4513
Epoch 140/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8283 - loss: 0.3951 - val_accuracy: 0.7994 - val_loss: 0.4553
Epoch 141/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8248 - loss: 0.3954 - val_accuracy: 0.8037 - val_loss: 0.4545
Epoch 142/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8294 - loss: 0.3916 - val_accuracy: 0.8069 - val_loss: 0.4560
Epoch 143/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8302 - loss: 0.3938 - val_accuracy: 0.8044 - val_loss: 0.4528
Epoch 144/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8286 - loss: 0.3957 - val_accuracy: 0.8000 - val_loss: 0.4557
Epoch 145/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8258 - loss: 0.3971 - val_accuracy: 0.8000 - val_loss: 0.4554
Epoch 146/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8302 - loss: 0.3957 - val_accuracy: 0.8025 - val_loss: 0.4504
Epoch 147/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8266 - loss: 0.3960 - val_accuracy: 0.8019 - val_loss: 0.4550
Epoch 148/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8264 - loss: 0.3926 - val_accuracy: 0.8056 - val_loss: 0.4482
Epoch 149/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8278 - loss: 0.3913 - val_accuracy: 0.8019 - val_loss: 0.4579
Epoch 150/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8270 - loss: 0.3948 - val_accuracy: 0.7994 - val_loss: 0.4575
Epoch 151/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8281 - loss: 0.3984 - val_accuracy: 0.7981 - val_loss: 0.4604
Epoch 152/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8263 - loss: 0.3953 - val_accuracy: 0.8012 - val_loss: 0.4584
Epoch 153/500
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8283 - loss: 0.3916 - val_accuracy: 0.8019 - val_loss: 0.4575
Epoch 154/500

In [107]:
y_log=model.predict(x_test_scaled1)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

In [108]:
y_pred=np.where(y_log >0.5,1,0)

In [109]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test1,y_pred)

0.822

# find best value usinh keras tunning

In [63]:
# fine tune keras 
!pip install -U keras-tuner

Requirement already satisfied: keras-tuner in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (1.4.7)
Requirement already satisfied: keras in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from keras-tuner) (3.12.0)
Requirement already satisfied: packaging in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from keras-tuner) (24.2)
Requirement already satisfied: requests in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from keras-tuner) (2.32.4)
Requirement already satisfied: kt-legacy in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from keras-tuner) (1.0.5)
Requirement already satisfied: absl-py in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from keras->keras-tuner) (2.3.1)
Requirement already satisfied: numpy in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from keras->keras-tuner) (2.2.0)
Requirement already satisfied: rich in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from keras->keras-tuner) (14.0.0)
Requirement already satisfied: namex in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from keras->keras-tuner) (3.15.1)
Requirement already satisfied: optree in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from keras->keras-tuner) (0.17.0)
Requirement already satisfied: ml-dtypes in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from keras->keras-tuner) (0.5.3)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from optree->keras->keras-tuner) (4.14.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from requests->keras-tuner) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from requests->keras-tuner) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from requests->keras-tuner) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from requests->keras-tuner) (2025.6.15)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from rich->keras->keras-tuner) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from rich->keras->keras-tuner) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\arind\appdata\local\programs\python\python313\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)

[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [64]:
import kerastuner as kt

C:\Users\arind\AppData\Local\Temp\ipykernel_12672\1654478174.py:1: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  import kerastuner as kt

In [65]:
from keras.models import Sequential
from keras.layers import Dense, BatchNormalization

def build_model2(hp):
    model2 = Sequential()

    num_layers = hp.Int('num_layers', min_value=1, max_value=10)

    for i in range(num_layers):
        # First hidden layer
        if i == 0:
            model2.add(
                Dense(
                    hp.Int('units' + str(i), min_value=8, max_value=128, step=8),
                    activation=hp.Choice('activation' + str(i), values=['relu', 'tanh']),
                    input_dim=4
                )
            )
            model2.add(Dropout(0.3),BatchNormalization())
        # Other hidden layers
        else:
            model2.add(
                Dense(
                    hp.Int('units' + str(i), min_value=8, max_value=128, step=8),
                    activation=hp.Choice('activation' + str(i), values=['relu', 'tanh'])
                )
            )
            model2.add(Dropout(0.2))
            

    # Output layer (for classification)
    model2.add(Dense(1, activation='sigmoid'))

    # Compile model
    model2.compile(
        optimizer=hp.Choice('optimizer', values=['Adam', 'rmsprop', 'SGD']),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model2

In [67]:
tuner=kt.RandomSearch(build_model2,objective='accuracy',max_trials=20,directory='my_dir',
    project_name='my_project6.5'
)

C:\Users\arind\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [66]:
from tensorflow.keras.callbacks import EarlyStopping
callbacks=[EarlyStopping(
    monitor="val_loss",
    min_delta=0.00001,
    patience=25,
    verbose=1,
    mode='auto',
    baseline=None,
    restore_best_weights=True)]

In [69]:
from tensorflow.keras.callbacks import EarlyStopping
callbacks=[EarlyStopping(
    monitor="accuracy",
    min_delta=0.005,
    patience=25,
    verbose=1,
    mode='auto',
    baseline=None,
    restore_best_weights=True)]
tuner.search(x_train_scaled1,y_train1,epochs=550,validation_data=(x_test_scaled1,y_test1),callbacks=callbacks)

Trial 15 Complete [00h 01m 10s]
accuracy: 0.8149999976158142

Best accuracy So Far: 0.8206250071525574
Total elapsed time: 00h 10m 57s

Search: Running Trial #16

Value             |Best Value So Far |Hyperparameter
9                 |5                 |num_layers
80                |128               |units0
tanh              |relu              |activation0
rmsprop           |rmsprop           |optimizer
24                |112               |units1
relu              |tanh              |activation1
112               |72                |units2
relu              |relu              |activation2
80                |8                 |units3
relu              |relu              |activation3
64                |112               |units4
relu              |relu              |activation4
48                |64                |units5
tanh              |tanh              |activation5
96                |128               |units6
relu              |tanh              |activation6
96                |None              |units7
tanh              |None              |activation7
40                |None              |units8
relu              |None              |activation8
64                |None              |units9
relu              |None              |activation9

Epoch 1/550

KeyboardInterrupt:

In [71]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 4,
 'units0': 72,
 'activation0': 'relu',
 'optimizer': 'Adam',
 'units1': 32,
 'activation1': 'tanh',
 'units2': 56,
 'activation2': 'tanh',
 'units3': 80,
 'activation3': 'relu',
 'units4': 120,
 'activation4': 'relu',
 'units5': 88,
 'activation5': 'tanh',
 'units6': 16,
 'activation6': 'tanh',
 'units7': 56,
 'activation7': 'relu',
 'units8': 8,
 'activation8': 'relu',
 'units9': 72,
 'activation9': 'relu'}

In [72]:
model2= tuner.get_best_models(num_models=1)[0]

C:\Users\arind\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\saving\saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 26 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [73]:
model2.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 72)                  │             360 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization                  │ (None, 72)                  │             288 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 32)                  │           2,336 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 56)                  │           1,848 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 80)                  │           4,560 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 1)                   │              81 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9,473 (37.00 KB)

 Trainable params: 9,329 (36.44 KB)

 Non-trainable params: 144 (576.00 B)

In [76]:
model2.fit(x_train_scaled1,y_train1,epochs=1100,initial_epoch=1001,validation_data=(x_test_scaled1,y_test1),verbose=True)

Epoch 1002/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.8171 - loss: 0.4172 - val_accuracy: 0.8275 - val_loss: 0.4082
Epoch 1003/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8188 - loss: 0.4148 - val_accuracy: 0.8255 - val_loss: 0.4069
Epoch 1004/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8200 - loss: 0.4139 - val_accuracy: 0.8265 - val_loss: 0.4074
Epoch 1005/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8179 - loss: 0.4149 - val_accuracy: 0.8205 - val_loss: 0.4064
Epoch 1006/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8192 - loss: 0.4131 - val_accuracy: 0.8270 - val_loss: 0.4087
Epoch 1007/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8177 - loss: 0.4125 - val_accuracy: 0.8245 - val_loss: 0.4096
Epoch 1008/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8223 - loss: 0.4113 - val_accuracy: 0.8250 - val_loss: 0.4096
Epoch 1009/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8194 - loss: 0.4132 - val_accuracy: 0.8275 - val_loss: 0.4122
Epoch 1010/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8195 - loss: 0.4128 - val_accuracy: 0.8275 - val_loss: 0.4071
Epoch 1011/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8186 - loss: 0.4121 - val_accuracy: 0.8210 - val_loss: 0.4091
Epoch 1012/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8199 - loss: 0.4102 - val_accuracy: 0.8260 - val_loss: 0.4089
Epoch 1013/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8206 - loss: 0.4117 - val_accuracy: 0.8290 - val_loss: 0.4088
Epoch 1014/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8196 - loss: 0.4131 - val_accuracy: 0.8270 - val_loss: 0.4097
Epoch 1015/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8199 - loss: 0.4126 - val_accuracy: 0.8250 - val_loss: 0.4093
Epoch 1016/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8214 - loss: 0.4106 - val_accuracy: 0.8235 - val_loss: 0.4063
Epoch 1017/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8196 - loss: 0.4116 - val_accuracy: 0.8205 - val_loss: 0.4065
Epoch 1018/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8206 - loss: 0.4111 - val_accuracy: 0.8295 - val_loss: 0.4091
Epoch 1019/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8206 - loss: 0.4112 - val_accuracy: 0.8210 - val_loss: 0.4082
Epoch 1020/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8179 - loss: 0.4131 - val_accuracy: 0.8295 - val_loss: 0.4070
Epoch 1021/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8192 - loss: 0.4112 - val_accuracy: 0.8230 - val_loss: 0.4080
Epoch 1022/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8220 - loss: 0.4093 - val_accuracy: 0.8205 - val_loss: 0.4086
Epoch 1023/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8220 - loss: 0.4095 - val_accuracy: 0.8300 - val_loss: 0.4074
Epoch 1024/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8196 - loss: 0.4102 - val_accuracy: 0.8220 - val_loss: 0.4096
Epoch 1025/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8201 - loss: 0.4106 - val_accuracy: 0.8255 - val_loss: 0.4073
Epoch 1026/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8239 - loss: 0.4084 - val_accuracy: 0.8225 - val_loss: 0.4076
Epoch 1027/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8215 - loss: 0.4111 - val_accuracy: 0.8265 - val_loss: 0.4057
Epoch 1028/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8216 - loss: 0.4080 - val_accuracy: 0.8260 - val_loss: 0.4133
Epoch 1029/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8189 - loss: 0.4129 - val_accuracy: 0.8250 - val_loss: 0.4101
Epoch 1030/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8232 - loss: 0.4089 - val_accuracy: 0.8245 - val_loss: 0.4087
Epoch 1031/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8219 - loss: 0.4114 - val_accuracy: 0.8245 - val_loss: 0.4090
Epoch 1032/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8191 - loss: 0.4092 - val_accuracy: 0.8245 - val_loss: 0.4112
Epoch 1033/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8211 - loss: 0.4078 - val_accuracy: 0.8265 - val_loss: 0.4086
Epoch 1034/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8202 - loss: 0.4082 - val_accuracy: 0.8245 - val_loss: 0.4071
Epoch 1035/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8215 - loss: 0.4094 - val_accuracy: 0.8240 - val_loss: 0.4076
Epoch 1036/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8238 - loss: 0.4080 - val_accuracy: 0.8265 - val_loss: 0.4083
Epoch 1037/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8226 - loss: 0.4074 - val_accuracy: 0.8230 - val_loss: 0.4090
Epoch 1038/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8220 - loss: 0.4084 - val_accuracy: 0.8290 - val_loss: 0.4084
Epoch 1039/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8201 - loss: 0.4090 - val_accuracy: 0.8260 - val_loss: 0.4100
Epoch 1040/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8214 - loss: 0.4075 - val_accuracy: 0.8260 - val_loss: 0.4116
Epoch 1041/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8205 - loss: 0.4085 - val_accuracy: 0.8245 - val_loss: 0.4112
Epoch 1042/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8219 - loss: 0.4074 - val_accuracy: 0.8235 - val_loss: 0.4101
Epoch 1043/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8207 - loss: 0.4088 - val_accuracy: 0.8235 - val_loss: 0.4058
Epoch 1044/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8223 - loss: 0.4064 - val_accuracy: 0.8265 - val_loss: 0.4082
Epoch 1045/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8214 - loss: 0.4067 - val_accuracy: 0.8255 - val_loss: 0.4145
Epoch 1046/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8229 - loss: 0.4059 - val_accuracy: 0.8245 - val_loss: 0.4103
Epoch 1047/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8224 - loss: 0.4059 - val_accuracy: 0.8190 - val_loss: 0.4111
Epoch 1048/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8206 - loss: 0.4075 - val_accuracy: 0.8255 - val_loss: 0.4103
Epoch 1049/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8196 - loss: 0.4096 - val_accuracy: 0.8250 - val_loss: 0.4099
Epoch 1050/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8190 - loss: 0.4081 - val_accuracy: 0.8205 - val_loss: 0.4101
Epoch 1051/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8227 - loss: 0.4061 - val_accuracy: 0.8250 - val_loss: 0.4108
Epoch 1052/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8223 - loss: 0.4073 - val_accuracy: 0.8225 - val_loss: 0.4104
Epoch 1053/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8226 - loss: 0.4088 - val_accuracy: 0.8240 - val_loss: 0.4083
Epoch 1054/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8214 - loss: 0.4053 - val_accuracy: 0.8235 - val_loss: 0.4093
Epoch 1055/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8221 - loss: 0.4070 - val_accuracy: 0.8215 - val_loss: 0.4131
Epoch 1056/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8235 - loss: 0.4034 - val_accuracy: 0.8235 - val_loss: 0.4167
Epoch 1057/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8227 - loss: 0.4074 - val_accuracy: 0.8180 - val_loss: 0.4116
Epoch 1058/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8217 - loss: 0.4073 - val_accuracy: 0.8250 - val_loss: 0.4118
Epoch 1059/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8215 - loss: 0.4061 - val_accuracy: 0.8185 - val_loss: 0.4113
Epoch 1060/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8205 - loss: 0.4076 - val_accuracy: 0.8290 - val_loss: 0.4070
Epoch 1061/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8254 - loss: 0.4038 - val_accuracy: 0.8205 - val_loss: 0.4101
Epoch 1062/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8250 - loss: 0.4048 - val_accuracy: 0.8230 - val_loss: 0.4080
Epoch 1063/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8225 - loss: 0.4047 - val_accuracy: 0.8255 - val_loss: 0.4103
Epoch 1064/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8229 - loss: 0.4064 - val_accuracy: 0.8245 - val_loss: 0.4096
Epoch 1065/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8221 - loss: 0.4055 - val_accuracy: 0.8190 - val_loss: 0.4093
Epoch 1066/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8240 - loss: 0.4054 - val_accuracy: 0.8245 - val_loss: 0.4118
Epoch 1067/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8219 - loss: 0.4037 - val_accuracy: 0.8230 - val_loss: 0.4098
Epoch 1068/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8244 - loss: 0.4040 - val_accuracy: 0.8235 - val_loss: 0.4172
Epoch 1069/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8196 - loss: 0.4072 - val_accuracy: 0.8240 - val_loss: 0.4122
Epoch 1070/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8205 - loss: 0.4044 - val_accuracy: 0.8225 - val_loss: 0.4121
Epoch 1071/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8239 - loss: 0.4038 - val_accuracy: 0.8215 - val_loss: 0.4125
Epoch 1072/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8263 - loss: 0.4042 - val_accuracy: 0.8220 - val_loss: 0.4112
Epoch 1073/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8217 - loss: 0.4035 - val_accuracy: 0.8245 - val_loss: 0.4097
Epoch 1074/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8255 - loss: 0.4033 - val_accuracy: 0.8270 - val_loss: 0.4126
Epoch 1075/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8253 - loss: 0.4022 - val_accuracy: 0.8230 - val_loss: 0.4115
Epoch 1076/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8204 - loss: 0.4047 - val_accuracy: 0.8260 - val_loss: 0.4119
Epoch 1077/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8221 - loss: 0.4041 - val_accuracy: 0.8235 - val_loss: 0.4138
Epoch 1078/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8248 - loss: 0.4038 - val_accuracy: 0.8240 - val_loss: 0.4123
Epoch 1079/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8250 - loss: 0.4025 - val_accuracy: 0.8205 - val_loss: 0.4102
Epoch 1080/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8246 - loss: 0.4033 - val_accuracy: 0.8210 - val_loss: 0.4127
Epoch 1081/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8230 - loss: 0.4044 - val_accuracy: 0.8240 - val_loss: 0.4102
Epoch 1082/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8245 - loss: 0.4018 - val_accuracy: 0.8250 - val_loss: 0.4107
Epoch 1083/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8224 - loss: 0.4021 - val_accuracy: 0.8155 - val_loss: 0.4158
Epoch 1084/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8234 - loss: 0.4047 - val_accuracy: 0.8225 - val_loss: 0.4089
Epoch 1085/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8245 - loss: 0.4009 - val_accuracy: 0.8260 - val_loss: 0.4168
Epoch 1086/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8220 - loss: 0.4013 - val_accuracy: 0.8215 - val_loss: 0.4132
Epoch 1087/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8221 - loss: 0.4028 - val_accuracy: 0.8215 - val_loss: 0.4155
Epoch 1088/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8231 - loss: 0.4024 - val_accuracy: 0.8265 - val_loss: 0.4098
Epoch 1089/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8232 - loss: 0.4040 - val_accuracy: 0.8265 - val_loss: 0.4106
Epoch 1090/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8232 - loss: 0.4027 - val_accuracy: 0.8220 - val_loss: 0.4110
Epoch 1091/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8215 - loss: 0.4035 - val_accuracy: 0.8225 - val_loss: 0.4145
Epoch 1092/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8216 - loss: 0.4023 - val_accuracy: 0.8205 - val_loss: 0.4126
Epoch 1093/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8221 - loss: 0.4009 - val_accuracy: 0.8245 - val_loss: 0.4164
Epoch 1094/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8235 - loss: 0.4028 - val_accuracy: 0.8255 - val_loss: 0.4120
Epoch 1095/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8265 - loss: 0.4019 - val_accuracy: 0.8220 - val_loss: 0.4164
Epoch 1096/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8214 - loss: 0.4050 - val_accuracy: 0.8230 - val_loss: 0.4131
Epoch 1097/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8239 - loss: 0.4018 - val_accuracy: 0.8230 - val_loss: 0.4125
Epoch 1098/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8269 - loss: 0.4008 - val_accuracy: 0.8270 - val_loss: 0.4125
Epoch 1099/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8242 - loss: 0.4026 - val_accuracy: 0.8205 - val_loss: 0.4178
Epoch 1100/1100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8273 - loss: 0.4010 - val_accuracy: 0.8200 - val_loss: 0.4136

In [113]:
y_log2=model2.predict(x_test_scaled1)

NameError: name 'model2' is not defined

In [79]:
y_pred2=np.where(y_log2 >0.5,1,0)

In [81]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test1,y_pred2)

0.826

In [111]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam, RMSprop, SGD
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
import keras_tuner as kt

def build_model2(hp):
    model2 = Sequential()

    # Tune number of hidden layers
    num_layers = hp.Int('num_layers', min_value=1, max_value=6)

    for i in range(num_layers):
        # Number of units per layer
        units = hp.Int('units_' + str(i), min_value=16, max_value=256, step=16)

        # Add dense layer
        if i == 0:
            model2.add(Dense(units, activation='relu', input_dim=10))
        else:
            model2.add(Dense(units, activation='relu'))

        # BatchNorm and Dropout
        model2.add(BatchNormalization())
        model2.add(Dropout(hp.Float('dropout_' + str(i), min_value=0.1, max_value=0.4, step=0.1)))

    # Output layer (Binary classification)
    model2.add(Dense(1, activation='sigmoid'))

    # Tune optimizer and learning rate
    optimizer_choice = hp.Choice('optimizer', ['adam', 'rmsprop', 'sgd'])
    learning_rate = hp.Float('learning_rate', min_value=1e-4, max_value=1e-2, sampling='log')

    if optimizer_choice == 'adam':
        optimizer = Adam(learning_rate=learning_rate)
    elif optimizer_choice == 'rmsprop':
        optimizer = RMSprop(learning_rate=learning_rate)
    else:
        optimizer = SGD(learning_rate=learning_rate, momentum=0.9)

    # Compile model
    model2.compile(
        optimizer=optimizer,
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model2

# --- Tuner ---
tuner = kt.RandomSearch(
    build_model2,
    objective='val_accuracy',
    max_trials=25,
    directory='my_dir',
    project_name='my_project5056'
)

# --- Callbacks ---
callbacks = [
    EarlyStopping(monitor='val_accuracy', patience=25, restore_best_weights=True, min_delta=0.005, verbose=1),
    ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=10, min_lr=1e-6, verbose=1)
]

# --- Search best model ---
tuner.search(
    x_train_scaled1, y_train1,
    validation_data=(x_test_scaled1, y_test1),
    epochs=300,
    callbacks=callbacks,
    verbose=1
)

Trial 25 Complete [00h 00m 38s]
val_accuracy: 0.8190000057220459

Best val_accuracy So Far: 0.8330000042915344
Total elapsed time: 00h 41m 00s

In [112]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 3,
 'units_0': 192,
 'dropout_0': 0.1,
 'optimizer': 'rmsprop',
 'learning_rate': 0.0003555649369416632,
 'units_1': 224,
 'dropout_1': 0.30000000000000004,
 'units_2': 160,
 'dropout_2': 0.30000000000000004,
 'units_3': 32,
 'dropout_3': 0.4,
 'units_4': 176,
 'dropout_4': 0.4,
 'units_5': 256,
 'dropout_5': 0.4}

In [114]:
model3= tuner.get_best_models(num_models=1)[0]

C:\Users\arind\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\saving\saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 16 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [115]:
model3.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 192)                 │             960 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization                  │ (None, 192)                 │             768 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 192)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 224)                 │          43,232 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_1                │ (None, 224)                 │             896 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 224)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 160)                 │          36,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ batch_normalization_2                │ (None, 160)                 │             640 │
│ (BatchNormalization)                 │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_2 (Dropout)                  │ (None, 160)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │             161 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 82,657 (322.88 KB)

 Trainable params: 81,505 (318.38 KB)

 Non-trainable params: 1,152 (4.50 KB)

In [116]:
model3.fit(x_train_scaled1,y_train1,epochs=500,initial_epoch=301,validation_data=(x_test_scaled1,y_test1),verbose=True)

Epoch 302/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.8109 - loss: 0.4304 - val_accuracy: 0.8300 - val_loss: 0.4069
Epoch 303/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8145 - loss: 0.4291 - val_accuracy: 0.8290 - val_loss: 0.4075
Epoch 304/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8161 - loss: 0.4303 - val_accuracy: 0.8300 - val_loss: 0.4055
Epoch 305/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8166 - loss: 0.4283 - val_accuracy: 0.8245 - val_loss: 0.4066
Epoch 306/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8129 - loss: 0.4281 - val_accuracy: 0.8235 - val_loss: 0.4073
Epoch 307/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8138 - loss: 0.4275 - val_accuracy: 0.8275 - val_loss: 0.4064
Epoch 308/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8159 - loss: 0.4262 - val_accuracy: 0.8260 - val_loss: 0.4066
Epoch 309/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8101 - loss: 0.4316 - val_accuracy: 0.8285 - val_loss: 0.4054
Epoch 310/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8117 - loss: 0.4305 - val_accuracy: 0.8245 - val_loss: 0.4063
Epoch 311/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8149 - loss: 0.4255 - val_accuracy: 0.8265 - val_loss: 0.4078
Epoch 312/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8170 - loss: 0.4261 - val_accuracy: 0.8275 - val_loss: 0.4092
Epoch 313/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8159 - loss: 0.4236 - val_accuracy: 0.8280 - val_loss: 0.4069
Epoch 314/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8163 - loss: 0.4228 - val_accuracy: 0.8260 - val_loss: 0.4070
Epoch 315/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8151 - loss: 0.4241 - val_accuracy: 0.8320 - val_loss: 0.4097
Epoch 316/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8179 - loss: 0.4230 - val_accuracy: 0.8275 - val_loss: 0.4055
Epoch 317/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8129 - loss: 0.4277 - val_accuracy: 0.8265 - val_loss: 0.4048
Epoch 318/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8186 - loss: 0.4264 - val_accuracy: 0.8315 - val_loss: 0.4055
Epoch 319/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8120 - loss: 0.4277 - val_accuracy: 0.8270 - val_loss: 0.4056
Epoch 320/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8131 - loss: 0.4238 - val_accuracy: 0.8255 - val_loss: 0.4049
Epoch 321/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8149 - loss: 0.4249 - val_accuracy: 0.8305 - val_loss: 0.4078
Epoch 322/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8144 - loss: 0.4258 - val_accuracy: 0.8310 - val_loss: 0.4070
Epoch 323/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8166 - loss: 0.4252 - val_accuracy: 0.8290 - val_loss: 0.4073
Epoch 324/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8133 - loss: 0.4258 - val_accuracy: 0.8315 - val_loss: 0.4078
Epoch 325/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8131 - loss: 0.4257 - val_accuracy: 0.8240 - val_loss: 0.4065
Epoch 326/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8158 - loss: 0.4261 - val_accuracy: 0.8265 - val_loss: 0.4060
Epoch 327/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8125 - loss: 0.4230 - val_accuracy: 0.8300 - val_loss: 0.4067
Epoch 328/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8154 - loss: 0.4262 - val_accuracy: 0.8235 - val_loss: 0.4077
Epoch 329/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8134 - loss: 0.4236 - val_accuracy: 0.8310 - val_loss: 0.4065
Epoch 330/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8163 - loss: 0.4212 - val_accuracy: 0.8310 - val_loss: 0.4070
Epoch 331/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8165 - loss: 0.4242 - val_accuracy: 0.8235 - val_loss: 0.4073
Epoch 332/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8160 - loss: 0.4243 - val_accuracy: 0.8290 - val_loss: 0.4080
Epoch 333/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8170 - loss: 0.4246 - val_accuracy: 0.8270 - val_loss: 0.4092
Epoch 334/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8135 - loss: 0.4223 - val_accuracy: 0.8225 - val_loss: 0.4054
Epoch 335/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8136 - loss: 0.4248 - val_accuracy: 0.8310 - val_loss: 0.4078
Epoch 336/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8156 - loss: 0.4247 - val_accuracy: 0.8265 - val_loss: 0.4083
Epoch 337/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8189 - loss: 0.4248 - val_accuracy: 0.8310 - val_loss: 0.4084
Epoch 338/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8167 - loss: 0.4270 - val_accuracy: 0.8275 - val_loss: 0.4082
Epoch 339/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8160 - loss: 0.4224 - val_accuracy: 0.8290 - val_loss: 0.4066
Epoch 340/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8164 - loss: 0.4212 - val_accuracy: 0.8275 - val_loss: 0.4102
Epoch 341/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8130 - loss: 0.4248 - val_accuracy: 0.8245 - val_loss: 0.4085
Epoch 342/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8174 - loss: 0.4253 - val_accuracy: 0.8275 - val_loss: 0.4090
Epoch 343/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8138 - loss: 0.4218 - val_accuracy: 0.8305 - val_loss: 0.4124
Epoch 344/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8169 - loss: 0.4220 - val_accuracy: 0.8275 - val_loss: 0.4123
Epoch 345/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8151 - loss: 0.4226 - val_accuracy: 0.8245 - val_loss: 0.4116
Epoch 346/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8131 - loss: 0.4217 - val_accuracy: 0.8290 - val_loss: 0.4074
Epoch 347/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8194 - loss: 0.4220 - val_accuracy: 0.8250 - val_loss: 0.4101
Epoch 348/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8160 - loss: 0.4250 - val_accuracy: 0.8265 - val_loss: 0.4071
Epoch 349/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8166 - loss: 0.4236 - val_accuracy: 0.8295 - val_loss: 0.4092
Epoch 350/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8158 - loss: 0.4242 - val_accuracy: 0.8265 - val_loss: 0.4078
Epoch 351/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8155 - loss: 0.4209 - val_accuracy: 0.8275 - val_loss: 0.4096
Epoch 352/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8156 - loss: 0.4252 - val_accuracy: 0.8260 - val_loss: 0.4064
Epoch 353/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8188 - loss: 0.4223 - val_accuracy: 0.8240 - val_loss: 0.4094
Epoch 354/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8165 - loss: 0.4237 - val_accuracy: 0.8280 - val_loss: 0.4074
Epoch 355/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8156 - loss: 0.4233 - val_accuracy: 0.8270 - val_loss: 0.4107
Epoch 356/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8141 - loss: 0.4237 - val_accuracy: 0.8290 - val_loss: 0.4095
Epoch 357/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8148 - loss: 0.4240 - val_accuracy: 0.8280 - val_loss: 0.4076
Epoch 358/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8188 - loss: 0.4173 - val_accuracy: 0.8200 - val_loss: 0.4085
Epoch 359/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8177 - loss: 0.4196 - val_accuracy: 0.8250 - val_loss: 0.4103
Epoch 360/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8133 - loss: 0.4219 - val_accuracy: 0.8280 - val_loss: 0.4068
Epoch 361/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8186 - loss: 0.4217 - val_accuracy: 0.8270 - val_loss: 0.4080
Epoch 362/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8142 - loss: 0.4246 - val_accuracy: 0.8245 - val_loss: 0.4085
Epoch 363/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8160 - loss: 0.4223 - val_accuracy: 0.8275 - val_loss: 0.4078
Epoch 364/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8164 - loss: 0.4188 - val_accuracy: 0.8240 - val_loss: 0.4062
Epoch 365/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8163 - loss: 0.4233 - val_accuracy: 0.8245 - val_loss: 0.4070
Epoch 366/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8169 - loss: 0.4191 - val_accuracy: 0.8275 - val_loss: 0.4102
Epoch 367/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8163 - loss: 0.4239 - val_accuracy: 0.8280 - val_loss: 0.4112
Epoch 368/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8142 - loss: 0.4228 - val_accuracy: 0.8240 - val_loss: 0.4088
Epoch 369/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8152 - loss: 0.4250 - val_accuracy: 0.8250 - val_loss: 0.4073
Epoch 370/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8175 - loss: 0.4214 - val_accuracy: 0.8210 - val_loss: 0.4076
Epoch 371/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8180 - loss: 0.4191 - val_accuracy: 0.8260 - val_loss: 0.4141
Epoch 372/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8170 - loss: 0.4237 - val_accuracy: 0.8235 - val_loss: 0.4101
Epoch 373/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8180 - loss: 0.4232 - val_accuracy: 0.8240 - val_loss: 0.4076
Epoch 374/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8175 - loss: 0.4185 - val_accuracy: 0.8260 - val_loss: 0.4108
Epoch 375/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8165 - loss: 0.4232 - val_accuracy: 0.8230 - val_loss: 0.4118
Epoch 376/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8166 - loss: 0.4235 - val_accuracy: 0.8255 - val_loss: 0.4085
Epoch 377/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8165 - loss: 0.4207 - val_accuracy: 0.8260 - val_loss: 0.4105
Epoch 378/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8159 - loss: 0.4217 - val_accuracy: 0.8245 - val_loss: 0.4086
Epoch 379/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8184 - loss: 0.4236 - val_accuracy: 0.8295 - val_loss: 0.4078
Epoch 380/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8171 - loss: 0.4216 - val_accuracy: 0.8320 - val_loss: 0.4095
Epoch 381/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8165 - loss: 0.4177 - val_accuracy: 0.8300 - val_loss: 0.4086
Epoch 382/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8169 - loss: 0.4230 - val_accuracy: 0.8310 - val_loss: 0.4091
Epoch 383/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8166 - loss: 0.4204 - val_accuracy: 0.8265 - val_loss: 0.4071
Epoch 384/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8175 - loss: 0.4220 - val_accuracy: 0.8275 - val_loss: 0.4096
Epoch 385/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8164 - loss: 0.4231 - val_accuracy: 0.8315 - val_loss: 0.4104
Epoch 386/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8190 - loss: 0.4193 - val_accuracy: 0.8265 - val_loss: 0.4094
Epoch 387/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8173 - loss: 0.4194 - val_accuracy: 0.8290 - val_loss: 0.4092
Epoch 388/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8163 - loss: 0.4203 - val_accuracy: 0.8280 - val_loss: 0.4081
Epoch 389/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8180 - loss: 0.4203 - val_accuracy: 0.8255 - val_loss: 0.4065
Epoch 390/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8189 - loss: 0.4204 - val_accuracy: 0.8245 - val_loss: 0.4123
Epoch 391/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8183 - loss: 0.4187 - val_accuracy: 0.8260 - val_loss: 0.4102
Epoch 392/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8190 - loss: 0.4188 - val_accuracy: 0.8290 - val_loss: 0.4119
Epoch 393/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8181 - loss: 0.4190 - val_accuracy: 0.8275 - val_loss: 0.4094
Epoch 394/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8158 - loss: 0.4215 - val_accuracy: 0.8230 - val_loss: 0.4084
Epoch 395/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8169 - loss: 0.4209 - val_accuracy: 0.8280 - val_loss: 0.4074
Epoch 396/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8188 - loss: 0.4234 - val_accuracy: 0.8265 - val_loss: 0.4068
Epoch 397/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8155 - loss: 0.4193 - val_accuracy: 0.8285 - val_loss: 0.4074
Epoch 398/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8179 - loss: 0.4239 - val_accuracy: 0.8280 - val_loss: 0.4099
Epoch 399/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8184 - loss: 0.4191 - val_accuracy: 0.8240 - val_loss: 0.4067
Epoch 400/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8158 - loss: 0.4224 - val_accuracy: 0.8245 - val_loss: 0.4069
Epoch 401/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8171 - loss: 0.4213 - val_accuracy: 0.8260 - val_loss: 0.4069
Epoch 402/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8201 - loss: 0.4172 - val_accuracy: 0.8290 - val_loss: 0.4090
Epoch 403/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8183 - loss: 0.4246 - val_accuracy: 0.8290 - val_loss: 0.4091
Epoch 404/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8176 - loss: 0.4231 - val_accuracy: 0.8295 - val_loss: 0.4065
Epoch 405/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8177 - loss: 0.4214 - val_accuracy: 0.8305 - val_loss: 0.4078
Epoch 406/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8160 - loss: 0.4188 - val_accuracy: 0.8240 - val_loss: 0.4097
Epoch 407/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8189 - loss: 0.4177 - val_accuracy: 0.8280 - val_loss: 0.4084
Epoch 408/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8141 - loss: 0.4212 - val_accuracy: 0.8255 - val_loss: 0.4077
Epoch 409/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8186 - loss: 0.4194 - val_accuracy: 0.8240 - val_loss: 0.4087
Epoch 410/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8179 - loss: 0.4222 - val_accuracy: 0.8260 - val_loss: 0.4082
Epoch 411/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8155 - loss: 0.4214 - val_accuracy: 0.8275 - val_loss: 0.4071
Epoch 412/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8169 - loss: 0.4208 - val_accuracy: 0.8275 - val_loss: 0.4061
Epoch 413/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8188 - loss: 0.4165 - val_accuracy: 0.8280 - val_loss: 0.4090
Epoch 414/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8180 - loss: 0.4190 - val_accuracy: 0.8240 - val_loss: 0.4073
Epoch 415/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8195 - loss: 0.4220 - val_accuracy: 0.8285 - val_loss: 0.4087
Epoch 416/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8151 - loss: 0.4212 - val_accuracy: 0.8255 - val_loss: 0.4084
Epoch 417/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8161 - loss: 0.4199 - val_accuracy: 0.8270 - val_loss: 0.4075
Epoch 418/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8150 - loss: 0.4193 - val_accuracy: 0.8275 - val_loss: 0.4067
Epoch 419/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8170 - loss: 0.4189 - val_accuracy: 0.8305 - val_loss: 0.4083
Epoch 420/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8165 - loss: 0.4223 - val_accuracy: 0.8260 - val_loss: 0.4090
Epoch 421/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8194 - loss: 0.4176 - val_accuracy: 0.8255 - val_loss: 0.4104
Epoch 422/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8169 - loss: 0.4221 - val_accuracy: 0.8280 - val_loss: 0.4094
Epoch 423/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8180 - loss: 0.4193 - val_accuracy: 0.8275 - val_loss: 0.4090
Epoch 424/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8174 - loss: 0.4205 - val_accuracy: 0.8270 - val_loss: 0.4080
Epoch 425/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8186 - loss: 0.4191 - val_accuracy: 0.8260 - val_loss: 0.4072
Epoch 426/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8176 - loss: 0.4205 - val_accuracy: 0.8245 - val_loss: 0.4078
Epoch 427/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8140 - loss: 0.4213 - val_accuracy: 0.8260 - val_loss: 0.4069
Epoch 428/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8144 - loss: 0.4217 - val_accuracy: 0.8290 - val_loss: 0.4087
Epoch 429/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8190 - loss: 0.4193 - val_accuracy: 0.8260 - val_loss: 0.4078
Epoch 430/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8140 - loss: 0.4235 - val_accuracy: 0.8270 - val_loss: 0.4060
Epoch 431/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8152 - loss: 0.4194 - val_accuracy: 0.8305 - val_loss: 0.4085
Epoch 432/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8158 - loss: 0.4197 - val_accuracy: 0.8240 - val_loss: 0.4078
Epoch 433/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8186 - loss: 0.4190 - val_accuracy: 0.8245 - val_loss: 0.4082
Epoch 434/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8173 - loss: 0.4209 - val_accuracy: 0.8245 - val_loss: 0.4088
Epoch 435/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8176 - loss: 0.4183 - val_accuracy: 0.8270 - val_loss: 0.4078
Epoch 436/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8192 - loss: 0.4227 - val_accuracy: 0.8220 - val_loss: 0.4085
Epoch 437/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8170 - loss: 0.4181 - val_accuracy: 0.8265 - val_loss: 0.4104
Epoch 438/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8194 - loss: 0.4173 - val_accuracy: 0.8265 - val_loss: 0.4097
Epoch 439/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8179 - loss: 0.4198 - val_accuracy: 0.8250 - val_loss: 0.4080
Epoch 440/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8210 - loss: 0.4154 - val_accuracy: 0.8285 - val_loss: 0.4106
Epoch 441/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8156 - loss: 0.4192 - val_accuracy: 0.8260 - val_loss: 0.4088
Epoch 442/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8195 - loss: 0.4164 - val_accuracy: 0.8280 - val_loss: 0.4068
Epoch 443/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8195 - loss: 0.4163 - val_accuracy: 0.8280 - val_loss: 0.4089
Epoch 444/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8156 - loss: 0.4163 - val_accuracy: 0.8270 - val_loss: 0.4090
Epoch 445/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8156 - loss: 0.4219 - val_accuracy: 0.8250 - val_loss: 0.4089
Epoch 446/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8177 - loss: 0.4192 - val_accuracy: 0.8230 - val_loss: 0.4072
Epoch 447/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8196 - loss: 0.4194 - val_accuracy: 0.8270 - val_loss: 0.4110
Epoch 448/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8188 - loss: 0.4181 - val_accuracy: 0.8230 - val_loss: 0.4089
Epoch 449/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8146 - loss: 0.4212 - val_accuracy: 0.8285 - val_loss: 0.4061
Epoch 450/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8207 - loss: 0.4173 - val_accuracy: 0.8230 - val_loss: 0.4093
Epoch 451/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8192 - loss: 0.4176 - val_accuracy: 0.8260 - val_loss: 0.4074
Epoch 452/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8189 - loss: 0.4190 - val_accuracy: 0.8240 - val_loss: 0.4073
Epoch 453/500
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.8177 - loss: 0.4206 - val_accuracy: 0.8230 - val_loss: 0.4062
Epoch 454/500

In [117]:
y_log3=model3.predict(x_test_scaled1)

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step

In [118]:
y_pred3=np.where(y_log3 >0.5,1,0)

In [119]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test1,y_pred3)

0.827